shellcheck

diff --git a/manjaro-backup b/manjaro-backup
--- a/manjaro-backup
+++ b/manjaro-backup
@@ -18,29 +18,29 @@ GRUB_40CONF="/etc/grub.d/40_custom"
 MAIN_LOOP=0
 
 function checkRoot {
-  if [[ "$EUID" -ne 0 ]]; then
+  if [[ "${EUID}" -ne 0 ]]; then
     printf "%b\n" "ERROR This script must be run as root. Use sudo." >&2
-    exit "$E_SUDO"
+    exit "${E_SUDO}"
   fi
 }
 
 function installUtils {
   for util in ${NEEDED_UTILS[*]}; do
-    if ! command -v "$util" ; then
-      { command pacman -Syq --noconfirm "$util"; } 2>&1
+    if ! command -v "${util}" ; then
+      command pacman -Syq --noconfirm "${util}" 1>/dev/null
     fi
   done
 }
 
 function parseISOFileName {
-  ISO_FILE="$( curl -s ${CLONEZILLA_URL}/MD5SUMS | grep "amd64.iso" |\
+  ISO_FILE="$( curl -s "${CLONEZILLA_URL}"/MD5SUMS | grep "amd64.iso" |\
                            awk '{print $2}' )"
 }
 
 function downloadISO {
-  if [[ -z "$ISO_FILE" ]]; then
+  if [[ -z "${ISO_FILE}" ]]; then
     printf "%b\n" "ERROR Empty download link." >&2
-    exit "$E_NOLINK"
+    exit "${E_NOLINK}"
     fi
   wget -qcO /opt/"${ISO_FILE}" "${CLONEZILLA_URL}/${ISO_FILE}"	
 }
@@ -48,11 +48,11 @@ function downloadISO {
 function checkISO_SUM {
   local MD5SUM
   local ISO_SUM
-  MD5SUM="$( curl -s ${CLONEZILLA_URL}/MD5SUMS | grep "amd64.iso" |\
+  MD5SUM="$( curl -s "${CLONEZILLA_URL}"/MD5SUMS | grep "amd64.iso" |\
                             awk '{print $1}' )"
   ISO_SUM="$( md5sum /opt/"${ISO_FILE}" | awk '{print $1}' )"
   if [[ "${ISO_SUM}" -ne "${MD5SUM}" ]]; then
-    printf "%b\n" "ERROR MD5SUM of $ISO_FILE is wrong." >&2
+    printf "%b\n" "ERROR MD5SUM of ${ISO_FILE} is wrong." >&2
     exit "${E_BADSUM}"
   fi
 }
@@ -81,7 +81,7 @@ EOF
 }
 
 function updateGRUB {
-  { command grub-mkconfig -o "${GRUB_40CONF}"; } 2>&1
+  command grub-mkconfig -o "${GRUB_40CONF}" 1>/dev/null
 }
 
 function checkConfFiles {
@@ -92,11 +92,11 @@ function checkConfFiles {
   printf "%s\n" " 1 - show ${GRUB_40CONF}"
   printf "%s\n" " 2 - edit ${GRUB_40CONF}"
   printf "%s\n" " 3 - exit"
-  until [[ $ANSWER =~ ^[1-3]$ ]]; do
+  until [[ ${ANSWER} =~ ^[1-3]$ ]]; do
     read -rp "Choise [1-3]: " -e -i 3 ANSWER
   done
 
-  case $ANSWER in
+  case ${ANSWER} in
     1)
       command less "${GRUB_40CONF}"
       ;;
@@ -106,6 +106,9 @@ function checkConfFiles {
     3)
       printf "%s\n" "Exit."
       MAIN_LOOP=1
+      ;;
+    *)
+      exit "${E_COMMON}"
       ;;
   esac
 }
@@ -123,5 +126,5 @@ function main {
   done
 }
 
-main "${@}" || exit "$E_COMMON"
+main "${@}" || exit "${E_COMMON}"
 exit 0
